### ISSUE TITLE
Simple test throws this error

### ISSUE THREAD

**Issue by Code4SAFrankie** [JulienPalard/grid-finder#1]
```
E:\WPy-3710\python-3.7.1.amd64>.\python.exe e:\Work\Python\grid_finder.py e:\Work\Python\chessboard.jpg --term
Traceback (most recent call last):
  File "e:\Work\Python\grid_finder.py", line 572, in <module>
    _main()
  File "e:\Work\Python\grid_finder.py", line 558, in _main
    img, grid = find_grid(args.file, args.debug)
  File "e:\Work\Python\grid_finder.py", line 523, in find_grid
    grid = Grid(warped_edges)
  File "e:\Work\Python\grid_finder.py", line 171, in __init__
    self.xpattern = LinePattern.infer(np.sum(lines, axis=1), min_x_step)
  File "e:\Work\Python\grid_finder.py", line 148, in infer
    return LinePattern(best[0], best[1])
  File "e:\Work\Python\grid_finder.py", line 111, in __init__
    self.start = start % step
ZeroDivisionError: integer division or modulo by zero
```

**Comment by JulienPalard** [comment]
Hi! You found an unmaintained project, sorry for that :(

I do not have time to contribute on this, but any PR is welcome :)
